apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  labels:
    app: notes-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: registry.me:5000/notesapp:0.0.1
          ports:
            - containerPort: 8080
